/* ══════════════════════════════════════════════════════════════════════
   INVENTORY — generated by admin.html on 2026-09-23, 10:56:29 PM

   You can edit this by hand, but it's easier to use admin.html.
   ══════════════════════════════════════════════════════════════════════ */

const INVENTORY = [
  {
    id: 5, name: "Beige sofa", brand: "Sofa Cycle Select",
    type: "sectional", colour: "—", dims: "—",
    condition: "Like New", price: 475,
    status: "available", img: "sofa-beige-sofa.jpg",
    photos: ["sofa-beige-sofa.jpg","sofa-beige-sofa-2.jpg","sofa-beige-sofa-3.jpg","sofa-beige-sofa-4.jpg","sofa-beige-sofa-5.jpg"],
    listed: "2026-09-24",
    note: "",
    hot: true
  },
  {
    id: 2, name: "IKEA Friheten Sofa Bed", brand: "IKEA Friheten",
    type: "sofa-bed", colour: "Warm Grey", dims: "230×151 cm",
    condition: "Like New", price: 600, rrp: 1099, fit: 30,
    status: "available", img: "sofa-friheten-bed.jpg",
    photos: ["sofa-friheten-bed.jpg"],
    listed: "2026-07-20",
    note: "Shown opened as a double bed. Converts back to a corner sofa with storage underneath.",
    hot: true
  }
];

/* Defense Sheets bundle pricing */
const SHEET_TIERS = [
  { qty: 1, price: 28, label: "1 Pack (12 sheets)" },
  { qty: 2, price: 49, label: "2 Packs (24 sheets)" },
  { qty: 3, price: 69, label: "3 Packs (36 sheets)" }
];

/* Cleaning service pricing */
const CLEANING = {
  tiers: [
    { name: "Loveseat / 2-Seater", price: 299, note: "Up to 2 cushions" },
    { name: "3-Seater Sofa",       price: 349, note: "Up to 3 cushions" },
    { name: "Sectional",           price: 429, note: "L-shape or larger" }
  ],
  addons: [
    { label: "🐾 Pet odour & hair treatment", price: 79 },
    { label: "🛡️ Fabric protection coating",  price: 69 },
    { label: "💧 Deep stain treatment",       price: 59 },
    { label: "🪑 Add an armchair",            price: 49 },
    { label: "🧴 Leather condition & polish", price: 39 }
  ]
};

if (typeof module !== "undefined") module.exports = { INVENTORY, SHEET_TIERS, CLEANING };
