/* ══════════════════════════════════════════════════════════════════════
   INVENTORY — generated by admin.html on 2026-09-23, 11:00:14 PM

   You can edit this by hand, but it's easier to use admin.html.
   ══════════════════════════════════════════════════════════════════════ */

const INVENTORY = [
  {
    id: 2, name: "IKEA Friheten Sofa Bed", brand: "IKEA Friheten",
    type: "sofa-bed", colour: "Warm Grey", dims: "230×151 cm",
    condition: "Like New", price: 600, rrp: 1099, fit: 30,
    status: "available", img: "sofa-friheten-bed.jpg",
    photos: ["sofa-friheten-bed.jpg"],
    listed: "2026-07-20",
    note: "Shown opened as a double bed. Converts back to a corner sofa with storage underneath.",
    hot: true
  },
  {
    id: 3, name: "Grey Sectional Sofa Bed", brand: "Sofa Cycle Select",
    type: "sofa-bed", colour: "Light Grey", dims: "240×150 cm",
    condition: "Like New", price: 575, was: 675, fit: 30,
    status: "available", img: "sofa-grey-tufted-bed.jpg",
    photos: ["sofa-grey-tufted-bed.jpg"],
    listed: "2026-07-15",
    note: "Tufted click-clack back, chrome legs, reversible chaise. Folds flat into a bed.",
    hot: true
  },
  {
    id: 4, name: "Brown Chaise Sectional", brand: "Sofa Cycle Select",
    type: "sectional", colour: "Mocha Brown", dims: "250×155 cm",
    condition: "Good", price: 450, fit: 30,
    status: "available", img: "sofa-brown-chaise.jpg",
    photos: ["sofa-brown-chaise.jpg"],
    listed: "2026-07-10",
    note: "Reversible chaise, deep comfortable seats. Neutral colour, light wear on the arms."
  }
];

/* Defense Sheets bundle pricing */
const SHEET_TIERS = [
  { qty: 1, price: 28, label: "1 Pack (12 sheets)" },
  { qty: 2, price: 49, label: "2 Packs (24 sheets)" },
  { qty: 3, price: 69, label: "3 Packs (36 sheets)" }
];

/* Cleaning service pricing */
const CLEANING = {
  tiers: [
    { name: "Loveseat / 2-Seater", price: 299, note: "Up to 2 cushions" },
    { name: "3-Seater Sofa",       price: 349, note: "Up to 3 cushions" },
    { name: "Sectional",           price: 429, note: "L-shape or larger" }
  ],
  addons: [
    { label: "🐾 Pet odour & hair treatment", price: 79 },
    { label: "🛡️ Fabric protection coating",  price: 69 },
    { label: "💧 Deep stain treatment",       price: 59 },
    { label: "🪑 Add an armchair",            price: 49 },
    { label: "🧴 Leather condition & polish", price: 39 }
  ]
};

if (typeof module !== "undefined") module.exports = { INVENTORY, SHEET_TIERS, CLEANING };
